language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
install:
  - pip install flake8==2.1.0 pep8==1.5.6 pyflakes==0.8.1
  - python setup.py install
  - pip list
script:
  - python setup.py test
  - flake8 pgqueue.py tests setup.py
matrix:
  allow_failures:
    - python: pypy
